// 曲検索
export const GET_TRACKS_START = "GET_TRACKS_START";
export const GET_TRACKS_SUCCESS = "GET_TRACKS_SUCCESS";
export const GET_TRACKS_FAILURE = "GET_TRACKS_FAILURE";

// アルバム検索
export const GET_ARTISTS_START = "GET_ARTISTS_START";
export const GET_ARTISTS_SUCCESS = "GET_ARTISTS_SUCCESS";
export const GET_ARTISTS_FAILURE = "GET_ARTISTS_FAILURE";

// アーティスト検索
export const GET_ALBUMS_START = "GET_ALBUMS_START";
export const GET_ALBUMS_SUCCESS = "GET_ALBUMS_SUCCESS";
export const GET_ALBUMS_FAILURE = "GET_ALBUMS_FAILURE";

// 1曲の基本情報取得 => tracksApi.tsで対応する
export const GET_TRACK_DETAILS_START = "GET_TRACK_DETAILS_START";
export const GET_TRACK_DETAILS_SUCCESS = "GET_TRACK_DETAILS_SUCCESS";
export const GET_TRACK_DETAILS_FAILURE = "GET_TRACK_DETAILS_FAILURE";

// 1曲のレーダーチャート用のパラメータ取得 => tracksApi.tsで対応する
export const GET_TRACK_PARAMETERS_START = "GET_TRACK_PARAMETERS_START";
export const GET_TRACK_PARAMETERS_SUCCESS = "GET_TRACK_PARAMETERS_SUCCESS";
export const GET_TRACK_PARAMETERS_FAILURE = "GET_TRACK_PARAMETERS_FAILURE";

// アーティストのTOP曲検索
export const GET_ARTIST_TOP_TRACK_START = "GET_ARTIST_TOP_TRACK_START";
export const GET_ARTIST_TOP_TRACK_SUCCESS = "GET_ARTIST_TOP_TRACK_SUCCESS";
export const GET_ARTIST_TOP_TRACK_FAILURE = "GET_ARTIST_TOP_TRACK_FAILURE";
