// 曲検索
export const GET_TRACKS_START = "GET_TRACKS_START";
export const GET_TRACKS_SUCCESS = "GET_TRACKS_SUCCESS";
export const GET_TRACKS_FAILURE = "GET_TRACKS_FAILURE";

// アルバム検索
export const GET_ARTISTS_START = "GET_ARTISTS_START";
export const GET_ARTISTS_SUCCESS = "GET_ARTISTS_SUCCESS";
export const GET_ARTISTS_FAILURE = "GET_ARTISTS_FAILURE";

// アーティスト検索
export const GET_ALBUMS_START = "GET_ALBUMS_START";
export const GET_ALBUMS_SUCCESS = "GET_ALBUMS_SUCCESS";
export const GET_ALBUMS_FAILURE = "GET_ALBUMS_FAILURE";